name: Scan Erreurs
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: https://noussaiba-r.github.io/Full_project/
          pages_path: ./
