// src/components/Icon.jsx
import {
  LayoutDashboard,
  FolderKanban,
  ClipboardList,
  Package,
  LogOut,
  Plus,
  CheckCircle,
  Clock,
  Users,
  Calendar,
  Settings,
  Wrench,
  QrCode,
  Filter,
  Search,
  User,
  ChevronDown,
  Box,
  Edit,
  Trash2,
  X,
  Cpu,
  ArrowRight,
} from 'lucide-react';

export const Icon = {
  dashboard: LayoutDashboard,
  projects: FolderKanban,
  requests: ClipboardList,
  output: Package, // أيقونة مناسبة لـ "Material Outputs"
  package: Package,
  logout: LogOut,
  plus: Plus,
  check: CheckCircle,
  clock: Clock,
  users: Users,
  calendar: Calendar,
  settings: Settings,
  maintenance: Wrench,
  scanner: QrCode,
  filter: Filter,
  search: Search,
  user: User,
  chevron: ChevronDown,
  box: Box,
  edit: Edit,
  trash: Trash2,
  close: X,
  chip: Cpu,
  arrow: ArrowRight,
};
